const AST: Vec<Expr> = vec![
    Expr::Op(
        Box::new(Expr::Sym('a')),
        Box::new(Expr::Sym('b')),
        Op::Equals,
    ),
    Expr::Op(
        Box::new(Expr::Sym('a')),
        Box::new(Expr::Op(
            Box::new(Expr::Val(-3.0)),
            Box::new(Expr::Val(5.0)),
            Op::Pow,
        )),
        Op::Equals,
    ),
    Expr::Op(
        Box::new(Expr::Sym('b')),
        Box::new(Expr::Op(
            Box::new(Expr::Op(
                Box::new(Expr::Val(5.0)),
                Box::new(Expr::Val(23.0)),
                Op::Pow,
            )),
            Box::new(Expr::Op(
                Box::new(Expr::Val(5.0)),
                Box::new(Expr::Val(21.0)),
                Op::Pow,
            )),
            Op::Frac,
        )),
        Op::Equals,
    ),
    Expr::Op(
        Box::new(Expr::Sym('b')),
        Box::new(Expr::Func(
            Func::Sqrt,
            vec![Expr::Op(
                Box::new(Expr::Val(5.0)),
                Box::new(Expr::Val(21.0)),
                Op::Pow,
            )],
        )),
        Op::Equals,
    ),
];
